// Generates dist/sw.js after a build, precaching exactly what the build
// produced. Runs as part of `npm run build`.
//
// The app has to work with the wifi off -- it lives on a tablet in a room with
// bad reception -- so the service worker precaches everything rather than
// caching opportunistically as pages are visited.
import { createHash } from 'node:crypto'
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const DIST = 'dist'

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name)
    return statSync(full).isDirectory() ? walk(full) : [full]
  })
}

const files = walk(DIST)
  .map((f) => relative(DIST, f).split('\\').join('/'))
  .filter((f) => f !== 'sw.js')
  .sort()

// Any change to any shipped byte gives a new cache name, so an old cache can
// never survive a deploy.
const hash = createHash('sha256')
for (const f of files) hash.update(f).update(readFileSync(join(DIST, f)))
const version = hash.digest('hex').slice(0, 12)

// The shell must be cached atomically or the app cannot boot offline. Fonts and
// icons are allowed to fail individually without failing the install.
const core = files.filter((f) => /\.(html|js|css)$/.test(f))
const extra = files.filter((f) => !core.includes(f))

const sw = `// Generated by scripts/make-sw.mjs -- do not edit.
const CACHE = 'homegym-${version}'
const CORE = ${JSON.stringify(core.map((f) => './' + f), null, 2)}
const EXTRA = ${JSON.stringify(extra.map((f) => './' + f), null, 2)}
const INDEX = new URL('./index.html', self.location.href).href

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE)
    await cache.addAll(CORE)
    await Promise.allSettled(EXTRA.map((url) => cache.add(url)))
    await self.skipWaiting()
  })())
})

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE) await caches.delete(key)
    }
    await self.clients.claim()
  })())
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  if (new URL(request.url).origin !== self.location.origin) return

  // The app never changes the URL, but a reload or a home-screen launch is a
  // navigation and must be served the shell whether or not there is a network.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const cached = await caches.match(INDEX)
      if (cached) return cached
      return fetch(request)
    })())
    return
  }

  event.respondWith((async () => {
    const cached = await caches.match(request)
    if (cached) return cached
    const response = await fetch(request)
    if (response.ok) {
      const cache = await caches.open(CACHE)
      cache.put(request, response.clone())
    }
    return response
  })())
})
`

writeFileSync(join(DIST, 'sw.js'), sw)
console.log(`sw.js: cache homegym-${version}, ${core.length} core + ${extra.length} other files`)
